### ISSUE TITLE
Will Shopware support this composerized way officially in the future?

### ISSUE THREAD

**Issue by DenisMir** [bcremer/shopware-composer-project#1]
Nice project. Coming from TYPO3 development which can be heavily composerized since 7LTS (being officially supported as the main way of working with TYPO3) I'm looking forward being able to work with Shopware the same way. 

Have you got some knowledge if this kind of having Shopware as a dependency will be officially supported in the future by Shopware directly?

**Comment by josh1va** [comment]
+1

**Comment by bcremer** [comment]
Disclaimer: I am a Shopware Employee.

At the moment this is a experiment driven mainly by me but I am very positive that this kind of composer support will make it into Shopware Core sooner or later.
