### ISSUE TITLE
Usable?

### ISSUE THREAD

**Issue by beyer-johannes** [bcremer/shopware-composer-project#2]
I know I´m late but why is this project not a stable solution to work with shopware projects?

Or is shopware easly usable as dependency with composer?

**Comment by mitelg** [comment]
hey @beyer-johannes 
we are currently working on a solution for the next version Shopware 5.4
https://github.com/shopware/shopware/tree/5.4

@bcremer is no longer a member of our team :wink:

**Comment by beyer-johannes** [comment]
Hi @mitelg 

thanks for the answer!

**Comment by bcremer** [comment]
That hurts @mitelg, I'm still a shopware team member by heart 💙

**Comment by mitelg** [comment]
I know, you will also be in our hearts :blush:
was not meant like this :wink:
